# Load dcm file

In [2]:
import numpy as np
import pydicom
import os


def load_dicom_images(dicom_dir):
    # Get list of DICOM files in the directory
    dicom_files = sorted([os.path.join(dicom_dir, file) for file in os.listdir(dicom_dir) if file.endswith('.dcm')])
    try:
        # Read DICOM files and stack pixel arrays into a 3D array
        dicom_data = [pydicom.dcmread(file) for file in dicom_files]
        preprocessed_image_data = np.stack([dicom.pixel_array for dicom in dicom_data])
        # Remove single channel dimension if present
        preprocessed_image_data = np.squeeze(preprocessed_image_data)
        return preprocessed_image_data
    except Exception as e:
        print("Error loading DICOM data:", e)
        return None


# Code for saving the slices

In [10]:
import os
import numpy as np
import matplotlib.pyplot as plt

def save_slices(output_dir, patient_id, datscan_date, dicom_images):
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Save axial slices 37 to 44 as PNG
    for slice_number in range(37, 45):
        output_filename = f"{slice_number}.png"
        patient_path = os.path.join(output_dir, patient_id)
        date_path = os.path.join(patient_path, datscan_date.split("_")[0])
        
        # Create the necessary directories if they don't exist
        os.makedirs(date_path, exist_ok=True)
        
        output_path = os.path.join(date_path, output_filename)
        try:
            if 0 <= slice_number < dicom_images.shape[0]:
                plt.imshow(dicom_images[slice_number, :, :], cmap='gray')
                plt.axis('off')
                
                # Check if file already exists
                if os.path.exists(output_path):
                    os.remove(output_path)
                    print(f"File {output_filename} already exists. Overwriting...")

                plt.savefig(output_path, bbox_inches='tight', pad_inches=0)
                plt.close()
                print(f"Saved axial slice {slice_number} as PNG:", output_path)
            else:
                print(f"Skipping out of bounds slice {slice_number} for Patient ID {patient_id}, DATSCAN Date {datscan_date}")
                break
        except IndexError:
            print(f"IndexError: Skipping DICOM images for Patient ID {patient_id}, DATSCAN Date {datscan_date}")
            break
        except Exception as e:
            print(f"Error saving axial slice {slice_number} for Patient ID {patient_id}, DATSCAN Date {datscan_date}: {e}")
            break
    else:
        print("All slices saved successfully.")


# Code for travers through the directories and save the slices

In [4]:
def traverse_directory(root_dir, output_root_dir):
    # Inside each group directory, look for patient directories
            for patient_id in os.listdir(root_dir):
                patient_dir = os.path.join(root_dir, patient_id)
                # output_patient_dir = os.path.join(output_group_dir, patient_id) # hear is a problem
                if os.path.isdir(patient_dir):
                    #  Inside each patient directory, look for Reconstructed_DaTSCAN directory
                    reconstructed_datscan_dir = os.path.join(patient_dir, "Reconstructed_DaTSCAN")
                    if os.path.isdir(reconstructed_datscan_dir):
                        # Inside Reconstructed_DaTSCAN, look for date folders
                        for date_folder in os.listdir(reconstructed_datscan_dir):
                            date_folder_path = os.path.join(reconstructed_datscan_dir, date_folder)
                            if os.path.isdir(date_folder_path):
                                # Inside each date folder, look for DATSCAN ID folders
                                for datscan_id_folder in os.listdir(date_folder_path):
                                    datscan_id_folder_path = os.path.join(date_folder_path, datscan_id_folder)
                                    if os.path.isdir(datscan_id_folder_path):
                                        # Inside each DATSCAN ID folder, load DICOM images and save axial slices
                                        dicom_images = load_dicom_images(datscan_id_folder_path)
                                        if dicom_images is not None:
                                            save_slices(output_root_dir, patient_id, date_folder, dicom_images) 

# Call the functions

In [12]:
#output folder path will be patient id/date/slice number.png
root_dir = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_v"
# Output directory to save PNG files for pd and hc groups
output_root = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
traverse_directory(root_dir, output_root)
print('done')

Saved axial slice 37 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\37.png
Saved axial slice 38 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\38.png
Saved axial slice 39 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\39.png
Saved axial slice 40 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\40.png
Saved axial slice 41 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\41.png
Saved axial slice 42 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\42.png
Saved axial slice 43 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\43.png
Saved axial slice 44 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices\101748\2021-05-18\44.png
All slices saved successfully.
Saved axial slice

In [13]:
#output folder path will be patient id/date/slice number.png
root_dir = r"B:\Sami Sir Research\Data set\Final Dataset v2\five_v"
# Output directory to save PNG files for pd and hc groups
output_root = r"B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices"
traverse_directory(root_dir, output_root)
print('done')

Saved axial slice 37 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\37.png
Saved axial slice 38 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\38.png
Saved axial slice 39 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\39.png
Saved axial slice 40 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\40.png
Saved axial slice 41 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\41.png
Saved axial slice 42 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\42.png
Saved axial slice 43 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\43.png
Saved axial slice 44 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\five_visit_slices\100001\2020-09-09\44.png
All slices saved successfully.
Saved axial slice

In [14]:
#output folder path will be patient id/date/slice number.png
root_dir = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_v" 
# Output directory to save PNG files for pd and hc groups
output_root = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
traverse_directory(root_dir, output_root)
print('done')

Saved axial slice 37 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\37.png
Saved axial slice 38 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\38.png
Saved axial slice 39 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\39.png
Saved axial slice 40 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\40.png
Saved axial slice 41 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\41.png
Saved axial slice 42 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\42.png
Saved axial slice 43 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\43.png
Saved axial slice 44 as PNG: B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices\100007\2020-11-10\44.png
All slices saved successfully.
Saved axi

# Function of KMC for segmentation 

In [3]:
from sklearn.cluster import KMeans
from PIL import Image


def kmeans_image(image_path, num_clusters,threshold=None):
    # Load the image
    img = Image.open(image_path)
    
    # Convert image to numpy array
    img_array = np.array(img)    
    # Apply threshold if provided 
    if threshold is not None:
        img_array[img_array < threshold] = 0
    # Flatten the image array to a 2D array of pixels
    pixels = img_array.reshape((-1, 3))
    
    # Initialize KMeans model
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    
    # Fit KMeans model to the pixels
    kmeans.fit(pixels)
    
    # Get the labels and cluster centers
    labels = kmeans.labels_
    cluster_centers = kmeans.cluster_centers_
    
    brightest_cluster_center = np.argmax(np.sum(cluster_centers, axis=1)) 
    a=cluster_centers[brightest_cluster_center]
    print(a)

    modified_cluster_centers = np.zeros_like(cluster_centers)
    # Set the brightest cluster center to its original value
    modified_cluster_centers[brightest_cluster_center] = cluster_centers[brightest_cluster_center]

    # Create a new image with the pixel values replaced by cluster centers
    compressed_img_array = modified_cluster_centers[labels].reshape(img_array.shape).astype(np.uint8)

    compressed_img = Image.fromarray(compressed_img_array)
    
    return compressed_img

# calculate symmetry score

In [3]:
def calculate_symmetry_score(image):
    # Assuming image is a numpy array representing the ROI
    height, width = image.shape
    
    # Split the image along the vertical axis
    left_half = image[:, :width // 2]
    right_half = image[:, width // 2:]
    
    # Calculate the number of symmetric pixels
    num_symmetric_pixels = np.sum(left_half == np.flip(right_half, axis=1))
    
    # Calculate the symmetry score
    symmetry_score = num_symmetric_pixels / (height * width)
    
    return symmetry_score

# Function Feature extraction code 

In [4]:
import os
import pandas as pd
from skimage import io, measure, feature, filters, img_as_ubyte, img_as_float
from skimage.feature import graycomatrix, graycoprops
from skimage.filters import gabor
from scipy.stats import skew, kurtosis
import numpy as np

# Define function to extract features from an image
def extract_features(image_gray):
    # Read the image and convert to float, scaled to [0, 1]
    # image = io.imread(image_path, as_gray=True)
    image = img_as_float(image_gray)  # Ensure the image is in float format and scaled between 0 and 1

    # Convert image to uint8 for specific operations
    image_uint8 = img_as_ubyte(image)

    # Extract region properties
    props = measure.regionprops(measure.label(image_uint8 > filters.threshold_otsu(image_uint8)))

    # Initialize feature dictionary
    features = {}

    if len(props) > 0:
        # Calculate basic region properties
        features['Area'] = props[0].area
        features['PA_ratio'] = props[0].perimeter / props[0].area
        features['Solidity'] = props[0].solidity
        if props[0].perimeter != 0:
            features['Circularity'] = 4 * np.pi * props[0].area / props[0].perimeter ** 2
        else:
            features['Circularity'] = 0  # or some appropriate value
        features['EquivDiameter'] = props[0].equivalent_diameter
       
        features['Extent'] = props[0].extent
        
        features['Major axis length'] = props[0].major_axis_length
        features['Minor axis length'] = props[0].minor_axis_length
        features['ConvexArea'] = props[0].convex_area
        features['FilledArea'] = props[0].filled_area
        # Calculate intensity features
        features['Mean'] = np.mean(image)
        features['Standard Deviation'] = np.std(image)
        features['Skewness'] = skew(image.flatten())
        features['Kurtosis'] = kurtosis(image.flatten())

        # Calculate Shannon Entropy
        entropy_image = filters.rank.entropy(image_uint8, np.ones((3, 3)))
        features['Shannon_Entropy'] = entropy_image.mean()

        # Calculate LBP features
        lbp = feature.local_binary_pattern(image_uint8, 8, 1, method='uniform')
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, 8 + 3), range=(0, 8 + 2))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-7)
        features['lbp_energy'] = (hist ** 2).sum()
        features['lbp_entropy'] = -(hist * np.log2(hist + 1e-7)).sum()

        # Calculate Gabor features
        gabor_filt_real, gabor_filt_imag = gabor(image, frequency=0.6)
        gabor_magnitude = np.sqrt(gabor_filt_real**2 + gabor_filt_imag**2)
        features['gabor_energy'] = (gabor_filt_real**2 + gabor_filt_imag**2).sum()
        gabor_magnitude = gabor_magnitude + 1e-7
        gabor_entropy = -(gabor_magnitude * np.log2(gabor_magnitude)).sum()
        features['gabor_entropy'] = gabor_entropy

        # Calculate texture features
        co_matrix = graycomatrix(image_uint8, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
        features['correlation'] = graycoprops(co_matrix, 'correlation')[0, 0]
        features['dissimilarity'] = graycoprops(co_matrix, 'dissimilarity')[0, 0]
        features['homogeneity'] = graycoprops(co_matrix, 'homogeneity')[0, 0]
        features['contrast'] = graycoprops(co_matrix, 'contrast')[0, 0]
        features['energy'] = graycoprops(co_matrix, 'energy')[0, 0]
        
        
        # symmetry_score = calculate_symmetry_score(image)
        # features['symmetry_score'] = symmetry_score

        # Add brightness feature
        features['brightness'] = np.mean(image)

    return features



# Functin for preprocess  then feature extraction

In [5]:
import os
import pandas as pd
import uuid


def process_patient_data(root_folder, csv_path, num_clusters, slice_range):
    all_patient_features = {}

    for patient_id_folder in os.listdir(root_folder):
        print(f" Working with patient no {patient_id_folder}")
        patient_id_path = os.path.join(root_folder, patient_id_folder)
        if os.path.isdir(patient_id_path):
            for visit_date_folder in os.listdir(patient_id_path):
                print(f" Visit no  {visit_date_folder}")
                visit_date_path = os.path.join(patient_id_path, visit_date_folder)
                slice_features = []
                if os.path.isdir(visit_date_path):
                    for slice_name in slice_range:
                        print(f" Slice No   {slice_name}")
                        slice_path = os.path.join(visit_date_path, slice_name + '.png')
                        if os.path.isfile(slice_path):
                            compressed_img = kmeans_image(slice_path, num_clusters)
                            compressed_img_array = np.array(compressed_img)
                            compressed_img_array[compressed_img_array != 0] = 255
                            modified_compressed_img = Image.fromarray(compressed_img_array)
                            modified_compressed_img_gray = modified_compressed_img.convert('L')
                            features = extract_features(modified_compressed_img_gray)
                            slice_features.append(features)

                slice_features_df = pd.DataFrame(slice_features) 
                mean_features = slice_features_df.mean()

                mean_features['Patient ID'] = patient_id_folder
                mean_features['Visit Date'] = visit_date_folder
                all_patient_features[uuid.uuid4()] = mean_features

    df = pd.DataFrame(all_patient_features).T
    df = df[['Patient ID', 'Visit Date'] + [col for col in df.columns if col not in ['Patient ID', 'Visit Date']]]

    df.to_csv(csv_path)



# Extract feature from 37 to 39 no slice for patient with four visit

In [6]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_37-39.csv"
num_clusters = 14
slice_range = ['37', '38', '39']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   37
[215.09191974 204.52223427 215.05043384]
 Slice No   38
[214.0425155  217.20667257 210.09152642]
 Slice No   39
[212.29465593 223.59260615 221.89970717]
 Visit no  2022-01-27
 Slice No   37
[208.22419707 213.41970689 208.24197069]
 Slice No   38
[208.92220727 211.07213997 211.13189771]
 Slice No   39
[227.46167558 215.62067736 208.65882353]
 Visit no  2022-07-27
 Slice No   37
[206.7192929  201.963121   218.75556233]
 Slice No   38
[209.45238095 212.0783208  213.76002506]
 Slice No   39
[215.60195155 219.86103634 215.57065949]
 Visit no  2023-08-16
 Slice No   37
[217.80766484 220.81242561 215.69174006]
 Slice No   38
[228.81578175 228.84188912 220.98826635]
 Slice No   39
[217.91931712 218.02549111 217.71538821]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   37
[215.54461716 215.4289004  208.19516408]
 Slice No   38
[213.28571429 214.88203912 213.23532899]
 Slice No   39
[213.22792023 210.86951567 

# Extract feature from 38 to 40 no slice for patient with four visit


In [7]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_38-40.csv"
num_clusters = 14
slice_range = ['38', '39', '40']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   38
[214.0425155  217.20667257 210.09152642]
 Slice No   39
[212.29465593 223.59260615 221.89970717]
 Slice No   40
[213.8646729  226.74392523 224.38542056]
 Visit no  2022-01-27
 Slice No   38
[208.92220727 211.07213997 211.13189771]
 Slice No   39
[227.46167558 215.62067736 208.65882353]
 Slice No   40
[211.58766667 226.35833333 218.79566667]
 Visit no  2022-07-27
 Slice No   38
[209.45238095 212.0783208  213.76002506]
 Slice No   39
[215.60195155 219.86103634 215.57065949]
 Slice No   40
[216.53169548 218.06339096 219.19411586]
 Visit no  2023-08-16
 Slice No   38
[228.81578175 228.84188912 220.98826635]
 Slice No   39
[217.91931712 218.02549111 217.71538821]
 Slice No   40
[223.17383995 232.78749159 219.19435104]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   38
[213.28571429 214.88203912 213.23532899]
 Slice No   39
[213.22792023 210.86951567 209.26381766]
 Slice No   40
[213.96571761 210.00929692 

# Extract feature from 39 to 41 no slice for patient with four visit

In [8]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_39-41.csv"
num_clusters = 14
slice_range = ['39', '40', '41']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   39
[212.29465593 223.59260615 221.89970717]
 Slice No   40
[213.8646729  226.74392523 224.38542056]
 Slice No   41
[213.16303531 223.48873028 225.98459805]
 Visit no  2022-01-27
 Slice No   39
[227.46167558 215.62067736 208.65882353]
 Slice No   40
[211.58766667 226.35833333 218.79566667]
 Slice No   41
[214.77389222 210.27449102 214.15161677]
 Visit no  2022-07-27
 Slice No   39
[215.60195155 219.86103634 215.57065949]
 Slice No   40
[216.53169548 218.06339096 219.19411586]
 Slice No   41
[211.64761905 214.40923521 224.21847042]
 Visit no  2023-08-16
 Slice No   39
[217.91931712 218.02549111 217.71538821]
 Slice No   40
[223.17383995 232.78749159 219.19435104]
 Slice No   41
[224.08974758 224.10906825 210.75818012]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   39
[213.22792023 210.86951567 209.26381766]
 Slice No   40
[213.96571761 210.00929692 214.98198722]
 Slice No   41
[212.60473168 213.25447201 

# Extract feature from 40 to 42 no slice for patient with four visit


In [9]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_40-42.csv"
num_clusters = 14
slice_range = ['40', '41', '42']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   40
[213.8646729  226.74392523 224.38542056]
 Slice No   41
[213.16303531 223.48873028 225.98459805]
 Slice No   42
[221.72493404 221.70382586 208.31398417]
 Visit no  2022-01-27
 Slice No   40
[211.58766667 226.35833333 218.79566667]
 Slice No   41
[214.77389222 210.27449102 214.15161677]
 Slice No   42
[209.0106863  216.54761339 215.04132035]
 Visit no  2022-07-27
 Slice No   40
[216.53169548 218.06339096 219.19411586]
 Slice No   41
[211.64761905 214.40923521 224.21847042]
 Slice No   42
[214.53247126 216.09396552 216.70344828]
 Visit no  2023-08-16
 Slice No   40
[223.17383995 232.78749159 219.19435104]
 Slice No   41
[224.08974758 224.10906825 210.75818012]
 Slice No   42
[219.45869711 211.09738079 225.98018805]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   40
[213.96571761 210.00929692 214.98198722]
 Slice No   41
[212.60473168 213.25447201 208.5118292 ]
 Slice No   42
[227.62639925 193.99533582 

# Extract feature from 41 to 43 no slice for patient with four visit


In [10]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_41-43.csv"
num_clusters = 14
slice_range = ['41', '42', '43']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   41
[213.16303531 223.48873028 225.98459805]
 Slice No   42
[221.72493404 221.70382586 208.31398417]
 Slice No   43
[211.51044551 206.52026177 211.02693179]
 Visit no  2022-01-27
 Slice No   41
[214.77389222 210.27449102 214.15161677]
 Slice No   42
[209.0106863  216.54761339 215.04132035]
 Slice No   43
[224.66563467 224.65263158 214.89380805]
 Visit no  2022-07-27
 Slice No   41
[211.64761905 214.40923521 224.21847042]
 Slice No   42
[214.53247126 216.09396552 216.70344828]
 Slice No   43
[218.61963374 215.23626539 215.16961873]
 Visit no  2023-08-16
 Slice No   41
[224.08974758 224.10906825 210.75818012]
 Slice No   42
[219.45869711 211.09738079 225.98018805]
 Slice No   43
[209.08221892 209.09633482 211.78355622]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   41
[212.60473168 213.25447201 208.5118292 ]
 Slice No   42
[227.62639925 193.99533582 196.05130597]
 Slice No   43
[212.86897767 212.37955347 

# Extract feature from 42 to 44 no slice for patient with four visit

In [11]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\four_visit_slices"
csv_path = "four_visit_feature_42-44.csv"
num_clusters = 14
slice_range = ['42', '43', '44']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 101748
 Visit no  2021-05-18
 Slice No   42
[221.72493404 221.70382586 208.31398417]
 Slice No   43
[211.51044551 206.52026177 211.02693179]
 Slice No   44
[208.82708493 208.86457536 207.29176231]
 Visit no  2022-01-27
 Slice No   42
[209.0106863  216.54761339 215.04132035]
 Slice No   43
[224.66563467 224.65263158 214.89380805]
 Slice No   44
[218.16090768 216.46003094 209.10830325]
 Visit no  2022-07-27
 Slice No   42
[214.53247126 216.09396552 216.70344828]
 Slice No   43
[218.61963374 215.23626539 215.16961873]
 Slice No   44
[215.05850763 212.40729226 208.32334652]
 Visit no  2023-08-16
 Slice No   42
[219.45869711 211.09738079 225.98018805]
 Slice No   43
[209.08221892 209.09633482 211.78355622]
 Slice No   44
[223.90620272 202.08018154 223.87783661]
 Working with patient no 103813
 Visit no  2021-08-26
 Slice No   42
[227.62639925 193.99533582 196.05130597]
 Slice No   43
[212.86897767 212.37955347 212.90599295]
 Slice No   44
[214.08420406 214.01843884 

# Extract feature from 37 to 39 no slice for patient with four visit


In [12]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_37-39.csv"
num_clusters = 14
slice_range = ['37', '38', '39']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   37
[222.43397001 219.80920107 217.01684124]
 Slice No   38
[216.26470588 216.36305882 217.52447059]
 Slice No   39
[202.05908203 201.31713867 222.0246582 ]
 Visit no  2022-01-19
 Slice No   37
[213.48151972 212.36650836 212.24509601]
 Slice No   38
[210.67903828 218.24673203 210.63818861]
 Slice No   39
[218.64252227 205.27543366 215.20511017]
 Visit no  2023-03-29
 Slice No   37
[218.99333333 219.06074074 218.94074074]
 Slice No   38
[213.07353464 212.48667851 212.76660746]
 Slice No   39
[208.04866619 208.2627974  208.018385  ]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   37
[214.36970863 212.73969214 213.24546454]
 Slice No   38
[209.61817184 213.03184189 212.34806478]
 Slice No   39
[228.89851916 210.36933798 220.48170732]
 Visit no  2021-12-14
 Slice No   37
[214.22238372 214.62063953 214.79408915]
 Slice No   38
[209.74085684 210.87565308 210.83019854]
 Slice No   39
[195.10978214 225.28961982 

# Extract feature from 38 to 40 no slice for patient with three visit


In [13]:

root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_38-40.csv"
num_clusters = 14
slice_range = ['38', '39', '40']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   38
[216.26470588 216.36305882 217.52447059]
 Slice No   39
[202.05908203 201.31713867 222.0246582 ]
 Slice No   40
[213.28523207 213.19803094 213.30351617]
 Visit no  2022-01-19
 Slice No   38
[210.67903828 218.24673203 210.63818861]
 Slice No   39
[218.64252227 205.27543366 215.20511017]
 Slice No   40
[211.02828706 229.43321111 205.18360398]
 Visit no  2023-03-29
 Slice No   38
[213.07353464 212.48667851 212.76660746]
 Slice No   39
[208.04866619 208.2627974  208.018385  ]
 Slice No   40
[205.07469512 205.08955793 205.00190549]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   38
[209.61817184 213.03184189 212.34806478]
 Slice No   39
[228.89851916 210.36933798 220.48170732]
 Slice No   40
[213.49836542 211.68034871 211.53541591]
 Visit no  2021-12-14
 Slice No   38
[209.74085684 210.87565308 210.83019854]
 Slice No   39
[195.10978214 225.28961982 192.11234515]
 Slice No   40
[210.8070357  210.8696327  

# Extract feature from 39 to 41 no slice for patient with three visit


In [14]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_39-41.csv"
num_clusters = 14
slice_range = ['39', '40', '41']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   39
[202.05908203 201.31713867 222.0246582 ]
 Slice No   40
[213.28523207 213.19803094 213.30351617]
 Slice No   41
[215.11776169 214.30261693 215.11108018]
 Visit no  2022-01-19
 Slice No   39
[218.64252227 205.27543366 215.20511017]
 Slice No   40
[211.02828706 229.43321111 205.18360398]
 Slice No   41
[212.03684573 203.82369146 213.14015152]
 Visit no  2023-03-29
 Slice No   39
[208.04866619 208.2627974  208.018385  ]
 Slice No   40
[205.07469512 205.08955793 205.00190549]
 Slice No   41
[203.7873101  212.82037534 198.52770331]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   39
[228.89851916 210.36933798 220.48170732]
 Slice No   40
[213.49836542 211.68034871 211.53541591]
 Slice No   41
[212.07669725 209.98642202 214.30458716]
 Visit no  2021-12-14
 Slice No   39
[195.10978214 225.28961982 192.11234515]
 Slice No   40
[210.8070357  210.8696327  214.41903777]
 Slice No   41
[209.00949914 208.91062176 

# Extract feature from 40 to 42 no slice for patient with three visit


In [15]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_40-42.csv"
num_clusters = 14
slice_range = ['40', '41', '42']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   40
[213.28523207 213.19803094 213.30351617]
 Slice No   41
[215.11776169 214.30261693 215.11108018]
 Slice No   42
[216.99862297 217.1635913  216.94629579]
 Visit no  2022-01-19
 Slice No   40
[211.02828706 229.43321111 205.18360398]
 Slice No   41
[212.03684573 203.82369146 213.14015152]
 Slice No   42
[198.30519734 209.84564283 210.26768269]
 Visit no  2023-03-29
 Slice No   40
[205.07469512 205.08955793 205.00190549]
 Slice No   41
[203.7873101  212.82037534 198.52770331]
 Slice No   42
[207.65432099 208.45631529 198.59876543]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   40
[213.49836542 211.68034871 211.53541591]
 Slice No   41
[212.07669725 209.98642202 214.30458716]
 Slice No   42
[211.22736182 211.02352019 213.61426891]
 Visit no  2021-12-14
 Slice No   40
[210.8070357  210.8696327  214.41903777]
 Slice No   41
[209.00949914 208.91062176 205.72063903]
 Slice No   42
[197.14578482 223.66185375 

# Extract feature from 41 to 43 no slice for patient with three visit

In [16]:
root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_41-43.csv"
num_clusters = 14
slice_range = ['41', '42', '43']
process_patient_data(root_folder, csv_path, num_clusters, slice_range)


 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   41
[215.11776169 214.30261693 215.11108018]
 Slice No   42
[216.99862297 217.1635913  216.94629579]
 Slice No   43
[205.91895078 215.15590922 207.05363985]
 Visit no  2022-01-19
 Slice No   41
[212.03684573 203.82369146 213.14015152]
 Slice No   42
[198.30519734 209.84564283 210.26768269]
 Slice No   43
[206.98661909 206.98037467 207.0396967 ]
 Visit no  2023-03-29
 Slice No   41
[203.7873101  212.82037534 198.52770331]
 Slice No   42
[207.65432099 208.45631529 198.59876543]
 Slice No   43
[209.5256167  208.90796964 208.95967742]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   41
[212.07669725 209.98642202 214.30458716]
 Slice No   42
[211.22736182 211.02352019 213.61426891]
 Slice No   43
[212.27144633 212.21632822 211.40696229]
 Visit no  2021-12-14
 Slice No   41
[209.00949914 208.91062176 205.72063903]
 Slice No   42
[197.14578482 223.66185375 207.42990219]
 Slice No   43
[206.69041201 215.19522526 

# Extract feature from 42 to 44 no slice for patient with three visit

In [17]:

root_folder = r"B:\Sami Sir Research\Data set\Final Dataset v2\three_visit_slices"
csv_path = "three_visit_feature_42-44.csv"
num_clusters = 14 
slice_range = ['42', '43', '44']

process_patient_data(root_folder, csv_path, num_clusters, slice_range)

 Working with patient no 100007
 Visit no  2020-11-10
 Slice No   42
[216.99862297 217.1635913  216.94629579]
 Slice No   43
[205.91895078 215.15590922 207.05363985]
 Slice No   44
[213.65785748 213.03586597 211.77866918]
 Visit no  2022-01-19
 Slice No   42
[198.30519734 209.84564283 210.26768269]
 Slice No   43
[206.98661909 206.98037467 207.0396967 ]
 Slice No   44
[208.97387897 202.85546365 209.07052677]
 Visit no  2023-03-29
 Slice No   42
[207.65432099 208.45631529 198.59876543]
 Slice No   43
[209.5256167  208.90796964 208.95967742]
 Slice No   44
[211.08920607 210.99687779 207.97636039]
 Working with patient no 100017
 Visit no  2020-11-20
 Slice No   42
[211.22736182 211.02352019 213.61426891]
 Slice No   43
[212.27144633 212.21632822 211.40696229]
 Slice No   44
[190.69121622 209.68716216 190.69391892]
 Visit no  2021-12-14
 Slice No   42
[197.14578482 223.66185375 207.42990219]
 Slice No   43
[206.69041201 215.19522526 206.38698498]
 Slice No   44
[219.76685515 203.78425402 

In [1]:
import os
import pandas as pd

def sort_csv_files(input_dir, output_dir):
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Loop through each file in the input directory
    for file_name in os.listdir(input_dir):
        if file_name.endswith('.csv'):
            # Construct full file path
            file_path = os.path.join(input_dir, file_name)
            
            # Read CSV file
            df = pd.read_csv(file_path)
            
            # Check if 'Patient ID' and 'Visit Date' columns exist
            if 'Patient ID' in df.columns and 'Visit Date' in df.columns:
                # Sort by 'Patient ID' and 'Visit Date'
                df_sorted = df.sort_values(by=['Patient ID', 'Visit Date'], ascending=True)
                
                # Construct output file path
                output_file_path = os.path.join(output_dir, file_name)
                
                # Save sorted DataFrame to new CSV file
                df_sorted.to_csv(output_file_path, index=False)
                print(f"Sorted file saved: {output_file_path}")
            else:
                print(f"'Patient ID' or 'Visit Date' column not found in {file_name}")

# Example usage
input_dir = r"B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\dataset"
output_dir = r"B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset"

sort_csv_files(input_dir, output_dir)


Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_37-39.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_38-40.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_39-41.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_40-42.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_41-43.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\four_visit_feature_42-44.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\mahbub\sorted_dataset\three_visit_feature_37-39.csv
Sorted file saved: B:\Projects\PycharmProjects\PPMI_Research_on_Parkinson's\src\ma